//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Tools.MigrateOldWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public long id { get; set; }
        public string text { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public System.DateTime added { get; set; }
        public int order { get; set; }
    }
}
