//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Tools.MigrateOldWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nikolayitEntities : DbContext
    {
        public nikolayitEntities()
            : base("name=nikolayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<background> backgrounds { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<config> configs { get; set; }
        public virtual DbSet<link> links { get; set; }
        public virtual DbSet<medium> media { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<posts_categories> posts_categories { get; set; }
        public virtual DbSet<project> projects { get; set; }
    }
}
