//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Tools.MigrateOldWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public long id { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string content { get; set; }
        public string content_short { get; set; }
        public System.DateTime published { get; set; }
        public System.DateTime last_update { get; set; }
        public string meta_description { get; set; }
        public string meta_keywords { get; set; }
        public string meta_robots { get; set; }
        public long background { get; set; }
    }
}
