//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Tools.MigrateOldWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts_categories
    {
        public long id { get; set; }
        public long post { get; set; }
        public long category { get; set; }
    }
}
